version: "3"

services:
  acmeair:
    container_name: acmeair
    image: acmeair-go
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - 8080:8080

  mongo:
    container_name: mongo
    image: mongo
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=acmeair
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
